export const AUTH_ATTEMPTING  = 'AUTH_ATTEMPTING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS' ;
export const AUTH_FAILD = 'AUTH_FAILD' ;
export const USER_LOGEDOUT = 'USER_LOGEDOUT' ;
export const FETCHED_PROFILE = 'FETCHED_PROFILE'
export const ADD_ERROR = 'ADD_errors'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const EXPENSE_SAVED = 'EXPENSE_SAVED'
export const FETCHED_FAILED = 'FETCHED_FAILED'
export const FETCHED_SUCCESS = 'FETCHED_SUCCESS'
export const FETCHING_EXPENSE = 'FETCHING_EXPENSE'
export const RESET_SAVED_FLAG = 'RESET_SAVED_FLAG'
export const REGISTER ='REGISTER'

